#端口配置
server:
    port: 8080
spring:
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:sqlserver://10.2.18.204;DatabaseName=hngx20180423
#      url: jdbc:sqlserver://192.168.1.92;DatabaseName=hngx20180421
      username: sa
      password: 123456
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
      # 下面为连接池的补充设置，应用到上面所有数据源中
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙(fqj于20180205去掉默认防火墙，允许sql批量执行，可在config中配置)
      filters: stat,slf4j
      logSlowSql: true
    http:
      encoding:
        force: true
        charset: utf-8
        enabled: true
    redis:
       # Redis数据库索引（默认为0）
      database: 0
      # Redis服务器地址
      host: 10.2.18.204
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      password: 123
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          maxActive: 20
         # 连接池最大阻塞等待时间（使用负值表示没有限制）
          maxWait: -1
         # 连接池中的最大空闲连接
          maxIdle: 20
          # 连接池中的最小空闲连接
          minIdle: 0
        # 连接超时时间（毫秒）
      timeout: 10000
    #activemq控制台端口 8161
    activemq:
      broker-url: tcp://10.2.18.204:61616
      user: admin
      password: admin
      in-memory: true
      # 如果此处设置为true，需要加activemq-pool的依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
      pool:
        enabled: false
    jpa:
        database: SQL_SERVER
        show-sql: true
        ddl-auto: create
        hibernate:
          naming-strategy:  org.hibernate.cfg.ImprovedNamingStrategy
        properties:
          hibernate:
            dialect: org.hibernate.dialect.SQLServer2008Dialect
    data:
        mongodb:
          database: bootmongodb
          uri: mongodb://10.2.18.204:27017
logging:
  config: classpath:logback.xml
  path: F:/logs
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.joy.mybatis.model
#pagehelper分页插件
pagehelper:
    helperDialect: sqlserver
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
# 系统常量配置
SysConstant:
  FTPpath: Z://
  mappedPath: file:D:/test/